"""
RoboAdvisor AI — Black-Litterman Portfolio Optimizer

Black-Litterman takes two inputs:
1. Market equilibrium returns (derived from market cap weights)
2. "Views" — subjective return expectations (in our case, generated by Claude)

It blends them based on confidence levels to produce optimal portfolio weights.

Reference: He & Litterman (1999), "The Intuition Behind Black-Litterman Model Portfolios"
"""

import numpy as np
from dataclasses import dataclass


@dataclass
class BLView:
    """A single investor view on an asset's expected return."""
    asset_index: int          # Index in the asset list
    expected_return: float    # Annual expected return (e.g., 0.12 = 12%)
    confidence: float         # 0.0 to 1.0, higher = more confident in this view


@dataclass
class BLResult:
    """Output of the Black-Litterman optimization."""
    weights: np.ndarray              # Optimal portfolio weights
    expected_returns: np.ndarray     # BL expected returns per asset
    tickers: list[str]
    portfolio_return: float          # Expected portfolio return
    portfolio_volatility: float      # Expected portfolio std dev
    sharpe_ratio: float              # Assuming risk-free rate
    
    def to_dict(self) -> dict:
        return {
            "weights": {t: round(float(w), 4) for t, w in zip(self.tickers, self.weights)},
            "expected_returns": {t: round(float(r), 4) for t, r in zip(self.tickers, self.expected_returns)},
            "portfolio_return": round(self.portfolio_return, 4),
            "portfolio_volatility": round(self.portfolio_volatility, 4),
            "sharpe_ratio": round(self.sharpe_ratio, 4),
        }


class BlackLittermanOptimizer:
    """
    Black-Litterman model implementation.
    
    Usage:
        optimizer = BlackLittermanOptimizer(
            tickers=["AAPL", "GOOGL", "MSFT", "AMZN"],
            market_caps=[3.0e12, 2.0e12, 2.8e12, 1.9e12],
            covariance_matrix=cov_matrix,  # (N x N) numpy array
            risk_free_rate=0.045,
        )
        
        views = [
            BLView(asset_index=0, expected_return=0.15, confidence=0.8),  # Bullish AAPL
            BLView(asset_index=2, expected_return=0.05, confidence=0.6),  # Bearish MSFT
        ]
        
        result = optimizer.optimize(views, tau=0.05, risk_aversion=2.5)
    """
    
    def __init__(
        self,
        tickers: list[str],
        market_caps: list[float],
        covariance_matrix: np.ndarray,
        risk_free_rate: float = 0.045,
    ):
        self.tickers = tickers
        self.n_assets = len(tickers)
        self.risk_free_rate = risk_free_rate
        
        # Market cap weights (equilibrium weights)
        caps = np.array(market_caps, dtype=float)
        self.market_weights = caps / caps.sum()
        
        # Covariance matrix (annualized)
        self.sigma = np.array(covariance_matrix, dtype=float)
        assert self.sigma.shape == (self.n_assets, self.n_assets), \
            f"Covariance matrix must be {self.n_assets}x{self.n_assets}"
    
    def _implied_equilibrium_returns(self, risk_aversion: float) -> np.ndarray:
        """
        Reverse-optimize to get implied equilibrium returns (pi).
        pi = risk_aversion * Sigma * w_market
        """
        return risk_aversion * self.sigma @ self.market_weights
    
    def _build_views(self, views: list[BLView]) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Build the P (pick matrix), Q (view returns), and Omega (view uncertainty) matrices.
        
        P: (K x N) — each row picks which asset the view is about
        Q: (K x 1) — expected return for each view
        Omega: (K x K) — diagonal, uncertainty of each view
        """
        k = len(views)
        
        P = np.zeros((k, self.n_assets))
        Q = np.zeros(k)
        omega_diag = np.zeros(k)
        
        for i, view in enumerate(views):
            P[i, view.asset_index] = 1.0
            Q[i] = view.expected_return
            
            # Omega = (1/confidence - 1) * variance of that asset
            # Higher confidence → lower uncertainty
            asset_var = self.sigma[view.asset_index, view.asset_index]
            confidence_clamped = np.clip(view.confidence, 0.01, 0.99)
            omega_diag[i] = ((1.0 / confidence_clamped) - 1.0) * asset_var
        
        Omega = np.diag(omega_diag)
        return P, Q, Omega
    
    def _bl_posterior_returns(
        self,
        pi: np.ndarray,
        P: np.ndarray,
        Q: np.ndarray,
        Omega: np.ndarray,
        tau: float,
    ) -> np.ndarray:
        """
        Compute Black-Litterman posterior expected returns.
        
        E[R] = [(tau * Sigma)^-1 + P' * Omega^-1 * P]^-1 
               * [(tau * Sigma)^-1 * pi + P' * Omega^-1 * Q]
        """
        tau_sigma_inv = np.linalg.inv(tau * self.sigma)
        omega_inv = np.linalg.inv(Omega)
        
        # Posterior precision (left side of the equation)
        posterior_precision = tau_sigma_inv + P.T @ omega_inv @ P
        
        # Posterior mean
        posterior_mean = np.linalg.inv(posterior_precision) @ (
            tau_sigma_inv @ pi + P.T @ omega_inv @ Q
        )
        
        return posterior_mean
    
    def _optimize_weights(
        self,
        expected_returns: np.ndarray,
        risk_aversion: float,
    ) -> np.ndarray:
        """
        Given BL returns, compute optimal weights.
        w* = (risk_aversion * Sigma)^-1 * E[R]
        
        Then normalize to sum to 1 and clamp to [0, 1] (long-only).
        """
        raw_weights = np.linalg.inv(risk_aversion * self.sigma) @ expected_returns
        
        # Long-only: clamp negatives to 0
        raw_weights = np.maximum(raw_weights, 0)
        
        # Normalize
        total = raw_weights.sum()
        if total > 0:
            weights = raw_weights / total
        else:
            # Fallback to equal weight
            weights = np.ones(self.n_assets) / self.n_assets
        
        return weights
    
    def optimize(
        self,
        views: list[BLView],
        tau: float = 0.05,
        risk_aversion: float = 2.5,
    ) -> BLResult:
        """
        Run the full Black-Litterman optimization.
        
        Args:
            views: List of BLView objects (Claude-generated market views)
            tau: Scalar, uncertainty in the prior (typical: 0.01 - 0.1)
            risk_aversion: Market risk aversion (typical: 2.0 - 4.0)
        
        Returns:
            BLResult with optimal weights and portfolio stats
        """
        if not views:
            raise ValueError("At least one view is required")
        
        # Step 1: Implied equilibrium returns
        pi = self._implied_equilibrium_returns(risk_aversion)
        
        # Step 2: Build view matrices
        P, Q, Omega = self._build_views(views)
        
        # Step 3: Black-Litterman posterior returns
        bl_returns = self._bl_posterior_returns(pi, P, Q, Omega, tau)
        
        # Step 4: Optimize weights
        weights = self._optimize_weights(bl_returns, risk_aversion)
        
        # Step 5: Portfolio statistics
        port_return = float(weights @ bl_returns)
        port_vol = float(np.sqrt(weights @ self.sigma @ weights))
        
        excess_return = port_return - self.risk_free_rate
        sharpe = excess_return / port_vol if port_vol > 0 else 0.0
        
        return BLResult(
            weights=weights,
            expected_returns=bl_returns,
            tickers=self.tickers,
            portfolio_return=port_return,
            portfolio_volatility=port_vol,
            sharpe_ratio=sharpe,
        )
    
    def optimize_no_views(self, risk_aversion: float = 2.5) -> BLResult:
        """
        Fallback: optimize using only equilibrium returns (no views).
        Equivalent to market-cap weighted portfolio.
        """
        pi = self._implied_equilibrium_returns(risk_aversion)
        weights = self.market_weights.copy()
        
        port_return = float(weights @ pi)
        port_vol = float(np.sqrt(weights @ self.sigma @ weights))
        
        excess_return = port_return - self.risk_free_rate
        sharpe = excess_return / port_vol if port_vol > 0 else 0.0
        
        return BLResult(
            weights=weights,
            expected_returns=pi,
            tickers=self.tickers,
            portfolio_return=port_return,
            portfolio_volatility=port_vol,
            sharpe_ratio=sharpe,
        )
