"""
RoboAdvisor AI — Data Models
All Pydantic models that flow through the agent graph.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


# ── Enums ──

class RiskTolerance(str, Enum):
    CONSERVATIVE = "conservative"      # 1-3
    MODERATE = "moderate"              # 4-6
    AGGRESSIVE = "aggressive"          # 7-9
    VERY_AGGRESSIVE = "very_aggressive" # 10


# ── Intake Agent Models ──

class InvestmentProfile(BaseModel):
    """Parsed from the user's natural language input."""
    capital: float = Field(..., description="Total investable amount in USD")
    risk_tolerance: int = Field(..., ge=1, le=10, description="1=conservative, 10=very aggressive")
    risk_category: RiskTolerance = Field(..., description="Derived from risk_tolerance score")
    horizon_years: float = Field(..., gt=0, description="Investment time horizon in years")
    sector_preferences: list[str] = Field(default_factory=list, description="Preferred sectors e.g. ['technology', 'energy']")
    constraints: list[str] = Field(default_factory=list, description="Exclusions e.g. ['no tobacco', 'no weapons']")
    existing_holdings: dict[str, float] = Field(default_factory=dict, description="Current positions {ticker: value}")
    raw_input: str = Field(..., description="Original user paragraph")
    session_id: Optional[str] = None


# ── Research Agent Models ──

class TechnicalIndicators(BaseModel):
    """Technical analysis signals for a single ticker."""
    rsi_14: Optional[float] = Field(None, description="14-day RSI (0-100)")
    macd: Optional[float] = Field(None, description="MACD line value")
    macd_signal: Optional[float] = Field(None, description="MACD signal line")
    macd_histogram: Optional[float] = Field(None, description="MACD histogram")
    sma_50: Optional[float] = Field(None, description="50-day simple moving average")
    sma_200: Optional[float] = Field(None, description="200-day simple moving average")
    bollinger_upper: Optional[float] = None
    bollinger_lower: Optional[float] = None
    bollinger_mid: Optional[float] = None


class Fundamentals(BaseModel):
    """Key fundamental metrics from Financial Modeling Prep."""
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    forward_pe: Optional[float] = None
    price_to_book: Optional[float] = None
    revenue_growth_yoy: Optional[float] = Field(None, description="Year-over-year revenue growth %")
    profit_margin: Optional[float] = None
    roe: Optional[float] = Field(None, description="Return on equity")
    debt_to_equity: Optional[float] = None
    dividend_yield: Optional[float] = None
    sector: Optional[str] = None
    industry: Optional[str] = None


class SentimentAnalysis(BaseModel):
    """News sentiment scored by Claude."""
    score: float = Field(..., ge=-1.0, le=1.0, description="-1=very bearish, 0=neutral, 1=very bullish")
    summary: str = Field(..., description="2-3 sentence news summary")
    num_articles: int = Field(0, description="Number of articles analyzed")
    top_headlines: list[str] = Field(default_factory=list)


class AssetResearch(BaseModel):
    """Complete research output for a single ticker."""
    ticker: str
    company_name: Optional[str] = None
    current_price: float
    currency: str = "USD"
    technicals: TechnicalIndicators
    fundamentals: Fundamentals
    sentiment: SentimentAnalysis
    fetched_at: datetime = Field(default_factory=datetime.utcnow)


# ── Strategy Agent Models ──

class AssetAllocation(BaseModel):
    """Single asset in the portfolio allocation."""
    ticker: str
    company_name: Optional[str] = None
    weight: float = Field(..., ge=0.0, le=1.0, description="Portfolio weight 0-1")
    shares: Optional[int] = Field(None, description="Approximate shares to buy")
    dollar_amount: Optional[float] = None
    rationale: str = Field(..., description="Why this allocation, generated by Claude")


class BlackLittermanParams(BaseModel):
    """Parameters used in the BL optimization — saved for reproducibility."""
    tau: float = Field(0.05, description="Scaling factor for uncertainty in prior")
    risk_aversion: float = Field(2.5, description="Market risk aversion parameter")
    view_confidences: dict[str, float] = Field(default_factory=dict, description="P matrix confidence per view")


class PortfolioStrategy(BaseModel):
    """Final output of the Strategy Agent."""
    session_id: Optional[str] = None
    allocations: list[AssetAllocation]
    expected_annual_return: float
    expected_volatility: float
    sharpe_ratio: float
    bl_params: BlackLittermanParams
    investment_profile: InvestmentProfile
    research_used: list[str] = Field(default_factory=list, description="Tickers that were researched")
    reasoning: str = Field(..., description="Claude's overall strategy explanation")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Conversation Memory ──

class Message(BaseModel):
    """Single message in the conversation."""
    role: str = Field(..., description="'user' or 'assistant'")
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Optional[dict] = Field(None, description="Agent name, tool calls, etc.")


class Session(BaseModel):
    """A full conversation session."""
    session_id: str
    messages: list[Message] = Field(default_factory=list)
    investment_profile: Optional[InvestmentProfile] = None
    strategy: Optional[PortfolioStrategy] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
